### ISSUE TITLE
[S_API FAIL] SteamAPI_Init() failed

### ISSUE THREAD

**Issue by RyougiShiki-214** [Left4DevOps/l4d2-docker#17]
Failed to start the l4d2 server in docker

System: Debian 12
docker-compose:
```
services:
  l4d2-server:
    image: left4devops/l4d2
    container_name: l4d2-server
    restart: unless-stopped
    volumes:
      - /root/shiki/data/docker-data/game-servers-data/l42d-data/addons:/addons
      - /root/shiki/data/docker-data/game-servers-data/l42d-data/cfg:/cfg
      - /root/shiki/data/docker-data/game-servers-data/l42d-data/motd:/motd
    ports:
      - "27015:27015"
      - "27015:27015/udp"
    network_mode: "bridge"
```
Log:
```
Redirecting stderr to '/home/louis/Steam/logs/stderr.txt'
Logging directory: '/home/louis/Steam/logs'
[  0%] Checking for available updates...
[----] Downloading update (0 of 52,274 KB)...
[  0%] Downloading update (57 of 52,274 KB)...
[ 27%] Downloading update (14,635 of 52,274 KB)...
[ 60%] Downloading update (32,137 of 52,274 KB)...
[100%] Downloading update (52,274 of 52,274 KB)...
[100%] Download complete.
[----] Installing update...
[----] Extracting package...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
UpdateUI: skip show logo
steamcmd.sh[7]: Restarting steamcmd by request...
Redirecting stderr to '/home/louis/Steam/logs/stderr.txt'
Logging directory: '/home/louis/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logo
Steam Console Client (c) Valve Corporation - version 1745270234
-- type 'quit' to exit --
Loading Steam API...OK
force_install_dir /home/louis/l4d2

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
app_update 222860
Success! App '222860' already up to date.
quit
Unloading Steam API...OK
Server will auto-restart if there is a crash.
Setting breakpad minidump AppID = 222860
Using breakpad crash handler
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API] SteamAPI_Init(): Loaded '/home/louis/.steam/sdk32/steamclient.so' OK.
#Using shader api: bin/shaderapiempty_srv.so
#
#Console initialized.
#Using breakpad minidump system
#Game_srv.so loaded for "Left 4 Dead 2"
Server is hibernating
ConVarRef test_progression_loop doesn't point to an existing ConVar
[S_API FAIL] SteamAPI_Init() failed; create pipe failed.Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
```
